### ISSUE TITLE
Notification link doesn't navigate to comment properly.

### ISSUE THREAD

**Issue by imbushuo** [nbdd0121/MW-FlowThread#12]
The notification link does navigate to the related page, but not the related comment.

![comments.PNG](https://ooo.0o0.ooo/2016/02/17/56c48d6d40472.png)

**Comment by nbdd0121** [comment]
'cuz I am too lazy

**Comment by nbdd0121** [comment]
Should be fixed in 3365338d6778bdc877707c8d588df330ca3658c9
