### ISSUE TITLE
用户名称占位符无法正常使用

### ISSUE THREAD

**Issue by yuronglong1996** [nbdd0121/MW-FlowThread#14]
我根据readme.md中
$wgFlowThreadConfig['Avatar'] (string), should be set to the URL of the avatar for registered user. You can use ${username} as a placeholder for user's name.
在LocalSettings.php中添加了一行
$wgFlowThreadConfig['Avatar'] = “$wgScriptPath/extensions/Avatar/avatar.php?user=${username}”;
但是在wiki测试中似乎并不能正常地工作，生成的image链接始终user=后为空
环境如下：
MediaWiki	1.28.0
PHP	5.6.29-0+deb8u1 (apache2handler)
MySQL	5.5.53-0+deb8u1
Lua	5.1.5

**Comment by nbdd0121** [comment]
PHP的双引号字符串里面`${xxx}`会被自动替换，你改成`$wgScriptPath . '/extensions/Avatar/avatar.php?user=${username}'` 试试
