### ISSUE TITLE
Error: could not import "mysql.sql" to the database

### ISSUE THREAD

**Issue by MagaFun** [nbdd0121/MW-FlowThread#15]
Just now I was trying to install FlowThread. When I was running `php update.php`, bash prompts the following error, saying cannot create a table:
`Creating FlowThread table ...[18c966156ebe2d550c1caea9] [no req]   MWException from line 2967 of /var/www/html/mydomain.com/public_html/wiki/includes/db/Database.php: Could not open "/var/www/html/mydomain.com/public_html/wiki/extensions/FlowThread/includes/sql/mysql.sql".`

I traced to `extensions/FlowThread/includes/` and I did not find `mysql.sql` in `sql/`. I then decided to copy `mysql.sql` in the `sql` folder into `FlowThread/includes/sql/` and run `php update.php` again. The process was a success. Is this intended or did I do something wrong?

**Comment by zoglun** [comment]
Either fix by move /sql/ to /includes/sql/ 
or
set $dir = __DIR__ . '/sql'; to $dir = ../sql/. '/sql'; in MW-FlowThread/includes/Hooks.php

**Comment by MagaFun** [comment]
Are you implying that this is a bug?

**Comment by zoglun** [comment]
Unfortunately I don't have rights to edit this repo.

**Comment by MagaFun** [comment]
Let's wait and see what `nbdd0121` would say.

**Comment by nbdd0121** [comment]
This is indeed a bug introduced when I move Hooks.php to includes. Thanks for the report and sorry for any inconvenience caused.
