### ISSUE TITLE
Reply in management page

### ISSUE THREAD

**Issue by CFSO6459** [nbdd0121/MW-FlowThread#2]
希望能（像多说一样）在 [[Special:管理FlowThread评论]] 里面巡查时，直接能回复他人在其他条目的评论。
update: 以及能够在评论管理界面点赞。

**Comment by nbdd0121** [comment]
I deliberately removed the functionality to view your own attitude about comments in management interface to reduce server load. I will do some tests to see the performance impact. As for replying in management page, it is doable.

**Comment by Walter0807** [comment]
It doesn't go with Echo now(perhaps for the sake of the version).
When running `php update.php`

> PHP Fatal error:  Class 'EchoBasicFormatter' not found in /var/lib/mediawiki/mediawiki-1.29.0/extensions/FlowThread/includes/Echo.php on line 232

Thanks!

**Comment by imbushuo** [comment]
> I deliberately removed the functionality to view your own attitude about comments in management interface to reduce server load.

@nbdd0121 I made it as a configurable switch in https://github.com/nbdd0121/MW-FlowThread/commit/2cae3990306d34da330c07a9dc55f1163c370c77 so you can test the impact on performance.

In-place reply in management page is doable but needs further evaluation.

**Comment by imbushuo** [comment]
”仔细想了想一共才多少个评论管理员有个毛性能影响“ —— nbdd0121

**Comment by nbdd0121** [comment]
剩下一个前端的 Reply 了，我想不出来这个 UI 怎么呈现，毕竟管理页面不是像普通页面的评论那样有层次关系

**Comment by imbushuo** [comment]
@nbdd0121 Just insert such replies as child nodes:
![image](https://user-images.githubusercontent.com/6284353/56626312-17f80080-65f6-11e9-95e0-83c18ecea3a5.png)

(Sorry Bilibili. I can't stop joking about your Global Security/CELA)

**Comment by nbdd0121** [comment]
What about the UI after commenting? Shall it stay there as a child node (which looks awkward compared to all other posts in the page, and also it requires an additional API call to fetch the posted comment) or make it disappear (which is much easier to implement, but is weird)?

**Comment by imbushuo** [comment]
I think just make it disappear, or insert a new comment entity on the top.

**Comment by nbdd0121** [comment]
Fixed in 7b6c726
