### ISSUE TITLE
时间显示错误

### ISSUE THREAD

**Issue by LovelyA72** [nbdd0121/MW-FlowThread#20]
评论框显示的时间都是1969年到1970年，这很明显不是期望的
![image](https://user-images.githubusercontent.com/29054052/34450068-c52344c0-ed3b-11e7-8695-d1ea02bae67d.png)

我的服务器是Windows XAMPP 3.2.2，PHP7.2.0，Apache 2.4.29
有问题的页面：所有页面
示例页面：https://www.yzwiki.com/item/User:A72  拖到最底就是评论框

**Comment by nbdd0121** [comment]
疑似是时间戳被截断了，在32位系统上可能会发生。你的PHP_INT_SIZE是多少？

**Comment by LovelyA72** [comment]
果然，换成32位Apache PHP就出这个问题了

**Comment by LovelyA72** [comment]
操作系统是64位的，但是Apache PHP是32位的

**Comment by LovelyA72** [comment]
PHP_INT_SIZE：4

**Comment by nbdd0121** [comment]
换用64位PHP即可

**Comment by LovelyA72** [comment]
如果技术限制无法更换怎么办

**Comment by LovelyA72** [comment]
Ok,这有一个比较特别的解决方案，那就是32位Apache用FCGI与64位PHP通信。这里把这个方法分享出来以备以后有人遇到同样的问题。但是这不是从程序上解决问题，所以close这个issue与否还是你决定吧，反正这个问题我解决了，谢谢了
