### ISSUE TITLE
Page attribute-based comment suppression

### ISSUE THREAD

**Issue by imbushuo** [nbdd0121/MW-FlowThread#21]
## Background

The current user opt-out feature implementation requires actions in both integrator's side and the [extension itself](https://github.com/nbdd0121/MW-FlowThread/blob/a78f2247054348b29b54e3a13b10e685b30f57cc/assets/flowthread.js#L8-L18). Or page has been pre-defined in the integration.

https://github.com/nbdd0121/MW-FlowThread/blob/a78f2247054348b29b54e3a13b10e685b30f57cc/assets/flowthread.js#L8-L18

https://github.com/nbdd0121/MW-FlowThread/blob/a78f2247054348b29b54e3a13b10e685b30f57cc/includes/Hooks.php#L41-L44

https://github.com/nbdd0121/MW-FlowThread/blob/a78f2247054348b29b54e3a13b10e685b30f57cc/includes/Hooks.php#L56-L59

Such soft constraint can be bypassed by invoking comment API directly. Hence, this design arises problems with third-party comment integration and manageability.

## Proposal

Implement a "magic word" that creates a new page attribute for suppressing comments in certain pages. For example, `__NOFLOWTHREAD__` maps to attribute `no_flow_thread`, then being processed during page submissions. Finally, when pages with such attribute are being rendered, hook function checks page attribute and decides whether to render comment block or not:

```php
$pageProps = PageProps::getInstance();
if (!empty($pageProps->getProperties($title, 'no_flow_thread'))) {
	return true;
}
```

Implement similar check routine in API backend. An error message should be returned when comment collections in such pages are being requested via API.

To prevent potential abuse, this magic word should be added or removed by certain privileged users. Additional abuse filter should be implemented along with this proposal.

**Comment by imbushuo** [comment]
@nbdd0121 comments?

**Comment by nbdd0121** [comment]
Use of magic word should not be a privileged operation. Making it privileged will cause confusion, as the same content saved by different users would have different effects. It would make more sense to make it similar to page protection.

**Comment by imbushuo** [comment]
Moved to #26
