### ISSUE TITLE
请问$wgFlowThreadConfig['Avatar']这个参数如何定义？

### ISSUE THREAD

**Issue by 651118109** [nbdd0121/MW-FlowThread#22]
按文档尝试了几次，分别填写
$wgFlowThreadConfig['Avatar'] = "$wgScriptPath/extensions/Avatar/avatar.php?user=username";
$wgFlowThreadConfig['Avatar'] = "$wgScriptPath/extensions/Avatar/avatar.php?user=${username} ";
都无法正常获取到头像，请问可以说明一下具体的设置吗？

**Comment by 651118109** [comment]
Avatar已经安装，目前问题是
$wgScriptPath/extensions/Avatar/avatar.php?user=
这一段，是可以正常获取到地址的
但是${username}获取到的值一直为空，设置后，从加载后的页面来看，就是用开发者工具直接指向网页的图片，图片处的地址是：src=“/extensions/Avatar/avatar.php?user=”

手动在浏览器输入https://example.com/extensions/Avatar/avatar.php?user=用户名
是可以正常跳转到头像图片的

把$wgScriptPath直接替换成https://example.com/的方式也尝试过了，我个人猜测主要还是${username}返回的是空值导致的原因

我当前填写的配置为：
wfLoadExtension('FlowThread');
wfLoadExtension('Avatar');
$wgFlowThreadConfig['Avatar'] = '$wgScriptPath/extensions/Avatar/avatar.php?user=${username}';

**Comment by baskice** [comment]
不清楚为什么，你可以尝试下调整加载顺序，改为
wfLoadExtension('Avatar');
wfLoadExtension('FlowThread');

**Comment by nbdd0121** [comment]
$wgFlowThreadConfig['Avatar'] = $wgScriptPath . '/extensions/Avatar/avatar.php?user=${username}';

一定要用单引号，不能用双引号

**Comment by 651118109** [comment]
fix了！ 十分感谢，另外建议在文档里说明，谢谢
