### ISSUE TITLE
该扩展在1.31下，永久删除无法正常工作

### ISSUE THREAD

**Issue by 651118109** [nbdd0121/MW-FlowThread#23]
mediawiki 版本1.31
管理后台处的，垃圾评论&被删除评论，操作永久删除无法生效，点击删除后，刷新页面又出来

为了排除问题
单独新建了1.31和1.30做排查，发现在1.30下永久删除工作正常

**Comment by nbdd0121** [comment]
error log里有什么错误消息吗

**Comment by 651118109** [comment]
> 
> 
> error log里有什么错误消息吗

我好像找到了，如果是 特殊:特殊页面-日志-评论日志 里面的话，可以看到由全部评论删除的操作，但是并没有永久删除的记录，而且也没有报错

**Comment by nbdd0121** [comment]
我是指的PHP的error log，应该可以在/var/log底下某处找到（有可能和web server在一起）

**Comment by 651118109** [comment]
> 
> 
> 我是指的PHP的error log，应该可以在/var/log底下某处找到（有可能和web server在一起）

尝试过执行操作后查看日志文件,但并没有输出相关错误
log_errors 已设置为on

**Comment by esuwiki** [comment]
https://github.com/esuweiki/MW-FlowThread/blob/master/includes/Post.php#L311

**Comment by 651118109** [comment]
> 
> 
> https://github.com/esuweiki/MW-FlowThread/blob/master/includes/Post.php#L311

thank
