### ISSUE TITLE
点击头像进入[[特殊:上传头像]]页面

### ISSUE THREAD

**Issue by CFSO6459** [nbdd0121/MW-FlowThread#3]
节操酱所说的issue包括评论区底端头像，以及右上角头像。

希望能够点击头像就进入增强版的[[特殊:上传头像]]页面。

附上程序媛群 2016-01-13 09:40:02 (GMT+8) Ben酱 对[[特殊:上传头像]]页面的想法：
![Image](http://i4.tietuku.com/f681253e1c2d17bf.jpg)

**Comment by nbdd0121** [comment]
Wrong repo. Please refer to the MW-Avatar repo to open issues about avatar.
