### ISSUE TITLE
能否发一个新版本来包含#34，方便主站升级

### ISSUE THREAD

**Issue by AnnAngela** [nbdd0121/MW-FlowThread#35]
如题（主要原因在于[有人反馈举报无用](https://zh.moegirl.org/Talk:%E6%8F%90%E9%97%AE%E6%B1%82%E5%8A%A9%E5%8C%BA#.E6.B1.82.E5.8A.A9.EF.BC.8C.E5.85.B3.E4.BA.8E.E9.83.A8.E5.88.86.E7.BD.91.E6.98.93.E4.BA.91.E9.9F.B3.E4.B9.90.E5.A4.96.E9.93.BE.E5.A4.B1.E6.95.88.E7.9A.84.E9.97.AE.E9.A2.98)，而我在[举报部分的第一页中](https://zh.moegirl.org/index.php?title=Special:%E7%AE%A1%E7%90%86FlowThread%E8%AF%84%E8%AE%BA&filter=reported)根本看不到这一条需要手动搜索，于是乎想让主站包含 #34 的改动）

**Comment by nbdd0121** [comment]
I've bumped the version. However it won't fix your issue, as after #34, the posts are sorted by their date of post, rather than date of last report.

**Comment by nbdd0121** [comment]
Also, issues are public -- you shouldn't include any non-public-accessible links.
