### ISSUE TITLE
关于cache-control header的控制问题

### ISSUE THREAD

**Issue by zoglun** [nbdd0121/MW-FlowThread#42]
当前获取评论默认cache-control: private, must-revalidate, max-age=0。导致每次访问都要回源确认。

例： https://zh.moegirl.org/api.php?action=flowthread&format=json&type=list&pageid=56129&offset=0&utf8=

插件内可否设置cache-control header？比如改为
cache-control: public, must-revalidate, max-age=60（1分钟后回源刷新）
可显著减轻热门条目对后端的压力。

**Comment by nbdd0121** [comment]
照设计 FlowThread 每次 API 调用需要的资源不高，而且我测过可以抗很高的并发，所以我就没开 cache。如果开了 cache-control 一个主要的问题是新发表一个评论以后没办法立即看到，这个是很反直觉的，导致用户可能重复发评论。

**Comment by zoglun** [comment]
实际负载不低。尤其是在有大量其他请求的生产环境，容易互相干扰。

 cache-control 对是否登陆区别设置即可，遵循mw默认设置，非登录public, max-age=18000 。登陆用户private, must-revalidate, max-age=0。
登陆用户当场看见内容即可。

**Comment by zoglun** [comment]
不知道你这说法是哪儿来的。cache-control header完全可以依照是否登陆返回不同结果，mw现行配置就是这样。
如果你不愿意写登陆状态判断，可以额外增加一个s-maxage=18000标签，其他不改动。即指示反向代理层（如squid/varnish/nginx cache/或外部cdn如cloudflare）缓存5小时。

**Comment by zoglun** [comment]
对于高访问压力，低更新频率场景，可以尽量将负载向边缘推。
比如指示边缘缓存节点无限期缓存，在内容更新时通过purge命令指示边缘节点更新缓存。在更新频繁的情况下设置一个延迟，比如1分钟内只发出一次purge请求。

wiki留言的场景对实时性要求并不高

**Comment by nbdd0121** [comment]
> 不知道你这说法是哪儿来的。cache-control header完全可以依照是否登陆返回不同结果，mw现行配置就是这样。

如果不加 Vary: Cookie，那 CDN 自然可以把已经缓存的 Public 内容推给已登录用户，加了 Vary: Cookie 的话因为萌百有 tracker cookie 的关系，每个人的 Cookie 都不一样，CDN 最后还是不能缓存。。

**Comment by zoglun** [comment]
并不是，现在使用cloudflare，仅在用户登陆有moegirlsso这个cookies时才bypass cache。

你不愿意做判断的话，可以加s-maxage，指示边缘缓存节点缓存一个时间。

**Comment by nbdd0121** [comment]
Fixed in 0efbfa4
