### ISSUE TITLE
管理FlowThread评论页无法显示评论

### ISSUE THREAD

**Issue by AnnAngela** [nbdd0121/MW-FlowThread#44]
管理FlowThread评论页不论使用何种选项都无法显示评论列表，打开开发者工具后发现获取评论的请求报如下错误：
````json
{
    "error":
    {
        "code": "unknown_type",
        "info": "Unrecognized value for parameter 'type': listall",
    }
}
````

**Comment by nbdd0121** [comment]
Invalid issue. Not reproducible with master. Likely a deployment issue.

**Comment by nbdd0121** [comment]
The listall API and the new management interface are introduced in 1.3.0. If you're referencing Moegirlpedia, https://zh.moegirl.org/Special:Version shows 1.2.0, so it must be a deployment issue. Contact the sysadmin of Moegirlpedia instead.

**Comment by zoglun** [comment]
That doesn't work for Moegirlpedia.
Using: Maser branch Flowthread (1.3.2 (0efbfa4))
Mediawiki:1.31.7

Internal Server Error
[1fd05826624169fea2c5d752] /api.php?action=flowthread&format=json&type=listall&utf8=&filter=normal&offset=0&limit=20&dir=older TypeError from line 19 of /mediawiki/extensions/FlowThread/includes/Helper.php: Argument 1 passed to FlowThread\Helper::buildPostInExpr() must be an instance of Wikimedia\Rdbms\DBConnRef, instance of Wikimedia\Rdbms\DatabaseMysqli given, called in /mediawiki/extensions/FlowThread/includes/Helper.php on line 88
Backtrace:
#0 /mediawiki/extensions/FlowThread/includes/Helper.php(88): FlowThread\Helper::buildPostInExpr(Wikimedia\Rdbms\DatabaseMysqli, array)
#1 /mediawiki/extensions/FlowThread/includes/API.php(11): FlowThread\Helper::batchGetUserAttitude(User, array)
#2 /mediawiki/extensions/FlowThread/includes/API.php(173): FlowThread\API->convertPosts(array, boolean, boolean)
#3 /mediawiki/extensions/FlowThread/includes/API.php(221): FlowThread\API->executeListAll()
#4 /mediawiki/includes/api/ApiMain.php(1579): FlowThread\API->execute()
#5 /mediawiki/includes/api/ApiMain.php(535): ApiMain->executeAction()
#6 /mediawiki/includes/api/ApiMain.php(506): ApiMain->executeActionWithErrorHandling()
#7 /mediawiki/api.php(94): ApiMain->execute()
#8 {main}

**Comment by RazeSoldier** [comment]
The master branch does not compatible with MW 1.31. You should fallback to the old version.
