### ISSUE TITLE
请问本插件是使用Cookies或缓存来保存zh-hans.json中的设置吗？

### ISSUE THREAD

**Issue by WinHGGG** [nbdd0121/MW-FlowThread#45]
本人使用MediaWiki搭建了一个[小站](https://wiki.sukasuka.cn)，引用了您的FlowThread拓展，并对zh-hans.json中的内容进行了修改。访问后修改的内容可以正常显示。
![](https://user-images.githubusercontent.com/31361289/80294766-6fe3bd00-879e-11ea-92c7-9f2c57cf4df2.png)

但是当本人访问同样使用此插件的H萌娘时，发现H萌娘的zh-hans.json并没有成功加载（亦或者使用了缓存中的zh-hans.json），导致评论区的提示信息出错。
![](https://user-images.githubusercontent.com/31361289/80294807-057f4c80-879f-11ea-9b03-76690c4c7eea.png)
![](https://user-images.githubusercontent.com/31361289/80294778-90137c00-879e-11ea-9746-82ee6ee08f56.png)

**Comment by nbdd0121** [comment]
You should not modify the source code, but rather MediaWiki:flowthread-ui-placeholder.
https://www.mediawiki.org/wiki/Help:System_message#Overriding_messages_on-wiki
