### ISSUE TITLE
Flowthread (1.3.2 (0efbfa4)) does not work for MW 1.31.7

### ISSUE THREAD

**Issue by zoglun** [nbdd0121/MW-FlowThread#46]
Using: Maser branch Flowthread (1.3.2 (0efbfa4))
Mediawiki:1.31.7

Comments failed to load as well as the control panel 

Internal Server Error
[1fd05826624169fea2c5d752] /api.php?action=flowthread&format=json&type=listall&utf8=&filter=normal&offset=0&limit=20&dir=older TypeError from line 19 of /mediawiki/extensions/FlowThread/includes/Helper.php: Argument 1 passed to FlowThread\Helper::buildPostInExpr() must be an instance of Wikimedia\Rdbms\DBConnRef, instance of Wikimedia\Rdbms\DatabaseMysqli given, called in /mediawiki/extensions/FlowThread/includes/Helper.php on line 88
Backtrace:
#0 /mediawiki/extensions/FlowThread/includes/Helper.php(88): FlowThread\Helper::buildPostInExpr(Wikimedia\Rdbms\DatabaseMysqli, array)
#1 /mediawiki/extensions/FlowThread/includes/API.php(11): FlowThread\Helper::batchGetUserAttitude(User, array)
#2 /mediawiki/extensions/FlowThread/includes/API.php(173): FlowThread\API->convertPosts(array, boolean, boolean)
#3 /mediawiki/extensions/FlowThread/includes/API.php(221): FlowThread\API->executeListAll()
#4 /mediawiki/includes/api/ApiMain.php(1579): FlowThread\API->execute()
#5 /mediawiki/includes/api/ApiMain.php(535): ApiMain->executeAction()
#6 /mediawiki/includes/api/ApiMain.php(506): ApiMain->executeActionWithErrorHandling()
#7 /mediawiki/api.php(94): ApiMain->execute()
#8 {main}

**Comment by zoglun** [comment]
Could you please to create a branch named like "1.31" for 6adb7738489d545e3c8dc9db13a12fd68260dad6

**Comment by zoglun** [comment]
Nope, git reset --hard 6adb773 does not work in our case. The last known working commit is fbf8a7f1026e3b696b687877da4732b6c7729152

**Comment by zoglun** [comment]
What I could confirmed now is that:
git reset --hard 4f1f11a work.

git reset --hard 6adb773 failed.

**Comment by RazeSoldier** [comment]
4f1f11a is correct. 6adb77 is break commit for MW 1.31.

**Comment by nbdd0121** [comment]
I no longer have a 1.31 environment. However I reverted relevant changes on branch [1.31-backport](https://github.com/nbdd0121/MW-FlowThread/tree/1.31-backport). You can check if that works.
