### ISSUE TITLE
出现InvalidArgumentException错误

### ISSUE THREAD

**Issue by 850710247liu** [nbdd0121/MW-FlowThread#49]
在管理评论界面点击用户发的评论的所在条目时，出现了以下错误：
[5168f7afbf1e95ebd587cd69] 2020-05-17 03:38:18: 类型“InvalidArgumentException”的致命错误
在通知里点击别人给我留言了这个通知也会出现这个问题，请问肿么才能解决

**Comment by nbdd0121** [comment]
如果可以的话最好提供一下stack trace

**Comment by nbdd0121** [comment]
至少也需要提供一下 MW 版本以及所使用的 FlowThread commit SHA

**Comment by 850710247liu** [comment]
就是二十天前那个问你Flowthread (1.3.2 (0efbfa4)) does not work for MW 1.31.7 的那个维基(萌娘百科)
