### ISSUE TITLE
希望能增加表情列表选择

### ISSUE THREAD

**Issue by 850710247liu** [nbdd0121/MW-FlowThread#54]
可以设计一个笑脸在左下角的眼睛旁边，点击后展开表情列表，供人选择。表情可以通过mw自己设计就最好了_(:з」∠)_

**Comment by 850710247liu** [comment]
啊啊啊，囧，有人已经写好评论区表情代码了，但是请问能简化一下吗，变成能编的mw界面一行一个表情就更好了，
源码 https://fgo.wiki/w/特殊:小工具

**Comment by nbdd0121** [comment]
这个功能无论如何都只能是前端实现（因为FlowThread只是接受Wikitext而已）。对于前端来说Module还是Gadget没有太大区别，建议您根据FGO Wiki的实现自行实现您想要的UI设计。
