### ISSUE TITLE
在MediaWiki:Flowthread-ui-placeholder里可以设计出未输入时评论框的灰底字，但不能识别灰底字的模板

### ISSUE THREAD

**Issue by 850710247liu** [nbdd0121/MW-FlowThread#56]
利用这个代码
{{#switch:{{#expr:{{伪随机数|1|{{#time:U}}}} mod 3}}
|#default=|0 = 随乐而起，有感而发...|1 = 万语千言，落笔汇成评论一句...|2 = 我不是针对谁，我是说在座的各位......}}
可以实现随机显示，但评论不读

**Comment by nbdd0121** [comment]
?没听懂你在说什么

**Comment by 850710247liu** [comment]
> ?没听懂你在说什么

就是未输入字时，评论框背景的灰字通过MediaWiki:Flowthread-ui-placeholder设计
在这个MW里不能识别模板和函数钩

**Comment by nbdd0121** [comment]
这个文本属于系统消息。前端的系统消息不支持模板和解析器函数，参见 https://www.mediawiki.org/wiki/Manual:Messages_API#Feature_support_in_JavaScript
