### ISSUE TITLE
Error怎么解决啊

### ISSUE THREAD

**Issue by rmolives** [nbdd0121/MW-FlowThread#65]
[8622bc9c04bdf5a41cd20aa8] Caught exception of type Error

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by White-NX** [comment]
#66 有说过v1.3.2不可以使用

直接Pull最新版本就好了

**Comment by RTR-RDD** [comment]
干啥？

**Comment by White-NX** [comment]
> 干啥？

看Issues然后挖坟（
