### ISSUE TITLE
目前最新版本不显示评论

### ISSUE THREAD

**Issue by seemoe** [nbdd0121/MW-FlowThread#67]
在管理FlowThread页面显示，但是在其他页面底下评论框不显示

**Comment by happyvalley-lmx** [comment]
When using MediaWiki 1.38.1 with MySQL 8.0.19 + nginx + PHP7.4 environment, same issue happened.  
Using MediaWiki 1.38.1 with MySQL  5.7.29 + nginx + PHP7.4 environment, all functional works normally.  
![P1](https://sm.ms/image/75vWcEnF8Tzj46R)  
![P2](https://sm.ms/image/i8B6aANM1VhoFUE)
