### ISSUE TITLE
All MediaWiki users' username are clickable, regardless of userpages' existence

### ISSUE THREAD

**Issue by imbushuo** [nbdd0121/MW-FlowThread#7]
In current design, all MediaWiki users' usernames are clickable, regardless of userpages' existence. But comments imported from Duoshuo, usernames are not clickable. So for users who don't have userpages, their usernames shouldn't be clickable.

**Comment by nbdd0121** [comment]
This is intended to facilitate users. Even their user page does not exist, there is a useful toolbar on the left and you can still click to view the user's talk page.
