### ISSUE TITLE
请求更改页面元素添加时间到DOM加载完成后

### ISSUE THREAD

**Issue by FlandreCirno** [nbdd0121/MW-FlowThread#72]
MW的ResourceLoader加载资源并不考虑页面是否加载完成，经常导致页面加载较慢、脚本加载较早时评论区不能被正确的添加到页面上，希望能修复一下这个问题。

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by nbdd0121** [comment]
Fixed in 4ee7bddaf7dd70e5d8dd7630b01e8a860f0494a9
