### ISSUE TITLE
MediaWiki 1.38 Closing Comment Section Bug

### ISSUE THREAD

**Issue by syccxcc** [nbdd0121/MW-FlowThread#74]
On MediaWiki 1.38, closing comment the section no longer works and it gives the following message:

![image](https://user-images.githubusercontent.com/12545295/201557791-14073b85-16f1-46f2-83e7-87f2620cf0f0.png)

This is due to api changes which resulted in a similar issue in [T280525](https://phabricator.wikimedia.org/T280525). The fix is to simply change the function call to `upsert` in `Control.php` to the newer version described in the [documentation](https://doc.wikimedia.org/mediawiki-core/master/php/interfaceWikimedia_1_1Rdbms_1_1IDatabase.html#a8d6992306577d84c6eac1eed6c04f325).

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by nbdd0121** [comment]
Fixed by #59
