### ISSUE TITLE
发布评论时出现错误

### ISSUE THREAD

**Issue by ethereal025** [nbdd0121/MW-FlowThread#76]
提交后出现“[Y6MJjlKpzONFDY5jCd-GZAAAABY] Caught exception of type Error”字样，依赖的插件已经装好了

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by nbdd0121** [comment]
Please try latest version
