### ISSUE TITLE
请问一下FlowThread的评论ID是如何计算的

### ISSUE THREAD

**Issue by xiaofeiTM233** [nbdd0121/MW-FlowThread#78]
如题，之前好像是找到是一个php函数直接生成的，现在找不到了
36进制直接逆向没看出是怎么算的

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by xiaofeiTM233** [comment]
I'm not sure if I didn't make myself clear enough

But the thing I'm talking about is $postid

Like this one![image](https://github.com/nbdd0121/MW-FlowThread/assets/55832499/e214800c-f9c9-4b11-be69-3b17ef516be1)

Because![image](https://github.com/nbdd0121/MW-FlowThread/assets/55832499/334fc548-07a9-433f-a234-809a1efc0523)

<details><summary>中文</summary>

我不确定我是否说得不够清楚

但是这个应该是 $postid

比如这个![image](https://github.com/nbdd0121/MW-FlowThread/assets/55832499/e214800c-f9c9-4b11-be69-3b17ef516be1)

因为![image](https://github.com/nbdd0121/MW-FlowThread/assets/55832499/334fc548-07a9-433f-a234-809a1efc0523)

</details>

**Comment by nbdd0121** [comment]
这是16进制，88位的 UID88

**Comment by xiaofeiTM233** [comment]
> 这是16进制，88位的 UID88

啊原来是16进制，我看到字母加数字以为是32

**Comment by xiaofeiTM233** [comment]
那么我应该怎样来计算一个id呢？比如通过具体时间计算出对应生成的id或者反过来？
只能通过这个接口跑一遍嘛？

**Comment by nbdd0121** [comment]
里面有 encode 时间。具体请参照 MediaWiki 代码中 newTimestampedUID88 的实现
